sh config_gen.sh Ga87 &
sh config_gen.sh Ga86 &
sh config_gen.sh Ga85 &
sh config_gen.sh Ga84 &
sh config_gen.sh Ga83 &
sh config_gen.sh Ni79 &
sh config_gen.sh Ni78 &
sh config_gen.sh Ni77 &
sh config_gen.sh Ni76 &
sh config_gen.sh Ni75 &
sh config_gen.sh Cu82 &
sh config_gen.sh Cu81 &
sh config_gen.sh Cu80 &
sh config_gen.sh Cu79 &
sh config_gen.sh Cu78 &
sh config_gen.sh Cu77 &
sh config_gen.sh Zn84 &
sh config_gen.sh Zn83 &
sh config_gen.sh Zn82 &
sh config_gen.sh Zn81 &
sh config_gen.sh Zn80 &
sh config_gen.sh Co73 &
sh config_gen.sh Co74 &
sh config_gen.sh Co75 &
sh config_gen.sh As88 &
sh config_gen.sh As89 &
sh config_gen.sh As90 &
sh config_gen.sh As91 &
sh config_gen.sh Ge85 &
sh config_gen.sh Ge86 &
sh config_gen.sh Ge87 &
sh config_gen.sh Ge88 &
sh config_gen.sh Ge89 &
