DISTANCE=${1}
sh configall.sh Ga87 ${DISTANCE} &
sh configall.sh Ga86 ${DISTANCE} &
sh configall.sh Ga85 ${DISTANCE} &
sh configall.sh Ga84 ${DISTANCE} &
sh configall.sh Ga83 ${DISTANCE} &
sh configall.sh Ni79 ${DISTANCE} &
sh configall.sh Ni77 ${DISTANCE} &
sh configall.sh Ni76 ${DISTANCE} &
sh configall.sh Ni75 ${DISTANCE} &
sh configall.sh Cu82 ${DISTANCE} &
sh configall.sh Cu81 ${DISTANCE} &
sh configall.sh Cu80 ${DISTANCE} &
sh configall.sh Cu79 ${DISTANCE} &
sh configall.sh Cu78 ${DISTANCE} &
sh configall.sh Cu77 ${DISTANCE} &
sh configall.sh Zn84 ${DISTANCE} &
sh configall.sh Zn83 ${DISTANCE} &
sh configall.sh Zn82 ${DISTANCE} &
sh configall.sh Zn81 ${DISTANCE} &
sh configall.sh Zn80 ${DISTANCE} &
sh configall.sh Co73 ${DISTANCE} &
sh configall.sh Co74 ${DISTANCE} &
sh configall.sh Co75 ${DISTANCE} &
sh configall.sh As88 ${DISTANCE} &
sh configall.sh As89 ${DISTANCE} &
sh configall.sh As90 ${DISTANCE} &
sh configall.sh As91 ${DISTANCE} &
sh configall.sh Ge85 ${DISTANCE} &
sh configall.sh Ge86 ${DISTANCE} &
sh configall.sh Ge87 ${DISTANCE} &
sh configall.sh Ge88 ${DISTANCE} &
sh configall.sh Ge89 ${DISTANCE} &
sh configall.sh Ni78 ${DISTANCE} 
