/** AidaTSScannor.hpp generated by R. Yokoyama 09/06/2018 **/

#ifndef VANDLE_MERGER_AIDATSSCANNOR_HPP_
#define VANDLE_MERGER_AIDATSSCANNOR_HPP_

#include "TSScannorBase.hpp"
#include "BRIKENTreeData.h"

/** timestamp scannor class for Aida events **/
class AidaTSScannor : public TSScannorBase<AidaTreeData>
{
public:
    const static std::string kMsgPrefix;
    AidaTSScannor(){}
    ~AidaTSScannor(){}
    void SetReader();

protected:
    ULong64_t GetTS() const
    {
        if(!tree_data_) throw kMsgPrefix + "In GetTS(), tree_data_ is null";
        if(!tree_data_->Get()) throw kMsgPrefix + "In GetTS(), tree_data_->Get() returned null";
        return tree_data_->Get()->T;
    }
};

#endif /* VANDLE_MERGER_AIDATSSCANNOR_HPP_ */
