/** BetaTSScannor.hpp generated by R. Yokoyama 09/06/2018 **/

#ifndef VANDLE_MERGER_BETATSSCANNOR_HPP_
#define VANDLE_MERGER_BETATSSCANNOR_HPP_

#include "ProcessorRootStruc.hpp"
#include "TSScannorBase.hpp"

/** timestamp scannor class for beta events **/
class BetaTSScannor : public TSScannorBase
{
public:
    const static std::string kMsgPrefix;
    BetaTSScannor(){}
    ~BetaTSScannor(){}
    void SetReader();

protected:
    /** energy gates on PSPMT dynode**/
    Double_t high_gain_min_;
    Double_t high_gain_max_;
    Double_t low_gain_min_;
    Double_t low_gain_max_;

    ULong64_t GetTS() const {return pixie_tree_data_->Get()->externalTS;}
    Bool_t IsInGate() const; // gate conditions
    TTreeReaderValue<PixTreeEvent> *pixie_tree_data_;
};

#endif /* VANDLE_MERGER_BETATSSCANNOR_HPP_ */
