/** BetaTSScannor.hpp generated by R. Yokoyama 09/06/2018 **/

#ifndef VANDLE_MERGER_BETATSSCANNOR_HPP_
#define VANDLE_MERGER_BETATSSCANNOR_HPP_

#include "TSScannorBase.hpp"
#include "ProcessorRootStruc.hpp"
#include "DumpTreeData.h"

/** timestamp scannor class for beta events **/
class BetaTSScannor : public TSScannorBase<PixTreeEvent>
{
public:
    const static std::string kMsgPrefix;
    BetaTSScannor(){}
    ~BetaTSScannor(){}
    void SetReader();

protected:
    /** energy gates on PSPMT dynode**/
    Double_t high_gain_min_;
    Double_t high_gain_max_;
    Double_t low_gain_min_;
    Double_t low_gain_max_;

    ULong64_t GetTS() const
    {
        if(!tree_data_) throw kMsgPrefix + "In GetTS(), tree_data_ is null";
        if(!tree_data_->Get()) throw kMsgPrefix + "In GetTS(), tree_data_->Get() returned null";
        return tree_data_->Get()->externalTS1;
    }

    Bool_t IsInGate() const; // gate conditions
};

/** timestamp scannor class for beta events **/
class BetaTSScannor2 : public TSScannorBase<DumpTreeData>
{
public:
    const static std::string kMsgPrefix;
    BetaTSScannor2(){}
    ~BetaTSScannor2(){}
    void SetReader();

protected:
    /** energy gates on PSPMT dynode**/
    Double_t high_gain_min_;
    Double_t high_gain_max_;
    Double_t low_gain_min_;
    Double_t low_gain_max_;

    ULong64_t GetTS() const
    {
        if(!tree_data_) throw kMsgPrefix + "In GetTS(), tree_data_ is null";
        if(!tree_data_->Get()) throw kMsgPrefix + "In GetTS(), tree_data_->Get() returned null";
        return tree_data_->Get()->externalTS1;
    }

    Bool_t IsInGate() const; // gate conditions
};
#endif /* VANDLE_MERGER_BETATSSCANNOR_HPP_ */
