/** BigRIPSTSScannor.hpp generated by R. Yokoyama 09/06/2018 **/

#ifndef VANDLE_MERGER_BIGRIPSTSSCANNOR_HPP_
#define VANDLE_MERGER_BIGRIPSTSSCANNOR_HPP_

#include "TSScannorBase.hpp"
#include "BigRIPSTreeData.h"

/** timestamp scannor class for BigRIPS events **/
class BigRIPSTSScannor : public TSScannorBase<TreeData>
{
public:
    const static std::string kMsgPrefix;
    BigRIPSTSScannor(){}
    ~BigRIPSTSScannor(){}
    void SetReader();

protected:
    ULong64_t GetTS() const {return tree_data_->Get()->ts;}
};

#endif /* VANDLE_MERGER_BIGRIPSTSSCANNOR_HPP_ */
