/** BigRIPSTSScannor.hpp generated by R. Yokoyama 09/06/2018 **/

#ifndef VANDLE_MERGER_BIGRIPSTSSCANNOR_HPP_
#define VANDLE_MERGER_BIGRIPSTSSCANNOR_HPP_

#include "TSScannorBase.hpp"

/** timestamp scannor class for BigRIPS events **/
class BigRIPSTSScannor : public TSScannorBase
{
public:
    const static std::string kMsgPrefix;
    BigRIPSTSScannor(){}
    ~BigRIPSTSScannor(){}
    void SetReader();

protected:
    ULong64_t GetTS() const {return *time_stamp_->Get();}
    TTreeReaderValue<ULong64_t> *time_stamp_;
};

#endif /* VANDLE_MERGER_BIGRIPSTSSCANNOR_HPP_ */
