/** BRIKENTSScannor.hpp generated by R. Yokoyama 09/15/2018 **/

#ifndef VANDLE_MERGER_BRIKENTSSCANNOR_HPP_
#define VANDLE_MERGER_BRIKENTSSCANNOR_HPP_

#include "TSScannorBase.hpp"
#include "BRIKENTreeData.h"

/** timestamp scannor class for BRIKEN events **/
class BRIKENTSScannor : public TSScannorBase<BRIKENTreeData>
{
public:
    const static std::string kMsgPrefix;
    BRIKENTSScannor(){}
    ~BRIKENTSScannor(){}
    void SetReader();

protected:
    ULong64_t GetTS() const
    {
        if(!tree_data_) throw kMsgPrefix + "In GetTS(), tree_data_ is null";
        if(!tree_data_->Get()) throw kMsgPrefix + "In GetTS(), tree_data_->Get() returned null";
        return tree_data_->Get()->T;
    }
};

#endif /* VANDLE_MERGER_BRIKENTSSCANNOR_HPP_ */
