/** E19044ImplantTSScanor.hpp generated by R. Yokoyama 10/25/2020 **/

#ifndef E19044_IMPLANTTSSCANOR_HPP_
#define E19044_IMPLANTTSSCANOR_HPP_

#include "ImplantTSScannor.hpp"
#include <TFile.h>
#include <TCutG.h>
#include <TTreeReaderValue.h>
#include "PaassRootStruct.hpp"

/** timestamp scannor class for implant events **/
class E19044ImplantTSScanor : public ImplantTSScannor
{
public:
    const static std::string kMsgPrefix;
    E19044ImplantTSScanor(){}
    virtual ~E19044ImplantTSScanor(){}
    void Configure(const std::string& yaml_node_name);
    void SetPidCut(TCutG* cut) { pid_cut_ = cut; }

protected:
    /** PID gate **/
    TCutG* pid_cut_ = nullptr;
    TTreeReaderValue<std::vector<processor_struct::PID>>* pid_data_;

    Bool_t IsInGate() override; // gate conditions
};

#endif /* E19044_IMPLANTTSSCANOR_HPP_ */
