/** TreeMerger.hpp generated by R. Yokoyama 09/07/2018 **/

#ifndef VANDLE_MERGER_TREEMERGER_HPP_
#define VANDLE_MERGER_TREEMERGER_HPP_

#include <TFile.h>
#include <TTreeReader.h>
#include <TTreeReaderValue.h>
#include "YamlReader.hpp"
#include "RemainTime.h"
#include "TSScannorBase.hpp"

/** merger class **/
// input_2 events will be merged to a vector in input_1

template <class T>
class TreeMerger
{
public:
    const static std::string kMsgPrefix;

    TreeMerger(){}
    TreeMerger(TSScannorBase* input1, TSScannorBase* input2);
    virtual ~TreeMerger();

    void Configure(const std::string &yaml_node_name);
    void Merge(); // scan through events from first_entry_ to last_entry_ of the tree

protected:
    TFile *tree_file_; // Output tree TFile
    YamlReader *yaml_reader_; // config reader
    RemainTime *remain_time_; // estimates remaining time
    ULong64_t print_freq_; // frequency to print scan progress
    T p_object_; // output class object

    /** timestamp scannors of input trees **/
    TSScannorBase *input_scannor_1_; 
    TSScannorBase *input_scannor_2_;

};

#endif /* VANDLE_MERGER_TREEMERGER_HPP_ */
