/** TSScannorBaseBase.hpp generated by R. Yokoyama 09/04/2018 **/

#ifndef VANDLE_MERGER_TSSCANNORBASE_HPP_
#define VANDLE_MERGER_TSSCANNORBASE_HPP_

#include <TFile.h>
#include <TTreeReader.h>
#include <TTreeReaderValue.h>
#include "YamlReader.hpp"
#include "RemainTime.h"
#include "ProcessorRootStruc.hpp"

/** Base class for scanning timestamp from tree **/
class TSScannorBase 
{
public:
    const static std::string kMsgPrefix;

    TSScannorBase();
    virtual ~TSScannorBase();

    void Configure(const std::string &yaml_node_name);
    virtual void SetReader(); // virtual function to define TTreeReaderValue
    void Scan(); // scan through events from first_entry_ to last_entry_ of the tree
    const std::map<ULong64_t,ULong64_t> &GetMap(){ return entry_ts_map_;}

protected:
    TFile *tree_file_; // Input tree TFile
    TTreeReader *tree_reader_; // TTreeReader
    YamlReader *yaml_reader_; // config reader
    std::map<ULong64_t,ULong64_t> entry_ts_map_; // map of key=index, value=timestamp
    RemainTime *remain_time_; // estimates remaining time
    ULong64_t first_entry_; // the index of the first entry to scan
    ULong64_t last_entry_; // the index of the last entry to scan
    ULong64_t print_freq_; // frequency to print scan progress

    virtual ULong64_t GetTS() const {return 0;}
    virtual Bool_t IsInGate() const {return true;}
};

#endif /* VANDLE_MERGER_TSSCANNORBASE_HPP_ */
