/** AidaTSScannor.cpp generated by R. Yokoyama 09/06/2018 **/
#include "AidaTSScannor.hpp"

const std::string AidaTSScannor::kMsgPrefix("[AidaTSScannor]:");

void AidaTSScannor::SetReader()
{
    TSScannorBase<TreeData>::SetReader();
    std::string br_name = yaml_reader_->GetString("BranchName");
    tree_data_ = new TTreeReaderValue<AidaTreeData>(*tree_reader_,br_name.c_str());
    std::cout << kMsgPrefix << "TTreeReaderValue: " << br_name << " created." << std::endl;
    return;
}

