/** BigRIPSTSScannor.cpp generated by R. Yokoyama 09/06/2018 **/
#include "BigRIPSTSScannor.hpp"

const std::string BigRIPSTSScannor::kMsgPrefix("[BigRIPSTSScannor]:");

void BigRIPSTSScannor::SetReader()
{
    TSScannorBase<TreeData>::SetReader();
    std::string br_name = yaml_reader_->GetString("BranchName");
    tree_data_ = new TTreeReaderValue<TreeData>(*tree_reader_,br_name.c_str());
    std::cout << kMsgPrefix << "TTreeReaderValue: " << br_name << " created." << std::endl;
    return;
}

Bool_t BigRIPSTSScannor::IsInGate() {
	auto sts = tree_data_->Get()->sts;
	if (sts == 0)
		return false;
	else
		return true;
}

