/** BRIKENTSScannor.cpp generated by R. Yokoyama 09/06/2018 **/
#include "BRIKENTSScannor.hpp"

const std::string BRIKENTSScannor::kMsgPrefix("[BRIKENTSScannor]:");

void BRIKENTSScannor::SetReader()
{
    TSScannorBase<TreeData>::SetReader();
    std::string br_name = yaml_reader_->GetString("BranchName");
    tree_data_ = new TTreeReaderValue<BRIKENTreeData>(*tree_reader_,br_name.c_str());
    std::cout << kMsgPrefix << "TTreeReaderValue: " << br_name << " created." << std::endl;
    return;
}

