/** E19044ImplantTSScanor.cpp generated by R. Yokoyama 09/06/2018 **/
#include "E19044ImplantTSScanor.hpp"

const std::string E19044ImplantTSScanor::kMsgPrefix("[E19044ImplantTSScanor]:");

void E19044ImplantTSScanor::Configure(const std::string& yaml_node_name) {
    TSScannorBase<PspmtData>::Configure(yaml_node_name);
    pid_data_ = new TTreeReaderValue<std::vector<processor_struct::PID>>(*tree_reader_,"pid_vec_");
    return;
}

Bool_t E19044ImplantTSScanor::IsInGate()
{
    if(!ImplantTSScannor::IsInGate())
        return false;
    
    if (!pid_cut_)
        return true;

    auto pid_vec = pid_data_->Get();
    if (pid_vec->empty())
        return false;
    if (pid_cut_->IsInside(pid_vec->at(0).pin_1_energy, pid_vec->at(0).pin_0_energy))
        return true;
    else
        return false;

}
