/** ImplantTSScannor.cpp generated by R. Yokoyama 09/06/2018 **/
#include "ImplantTSScannor.hpp"

const std::string ImplantTSScannor::kMsgPrefix("[ImplantTSScannor]:");

void ImplantTSScannor::SetReader()
{
    TSScannorBase<PspmtData>::SetReader();
    std::string br_name = yaml_reader_->GetString("PixieBranchName");
    tree_data_ = new TTreeReaderValue<PspmtData>(*tree_reader_,br_name.c_str());
    std::cout << kMsgPrefix << "TTreeReaderValue: " << br_name << " created." << std::endl;

    low_gain_min_ = yaml_reader_->GetDouble("MinLowGainDynEnergy");
    low_gain_max_ = yaml_reader_->GetDouble("MaxLowGainDynEnergy");
    std::cout << kMsgPrefix << "Implant range on dynode low gain: " << low_gain_min_ << " - " << low_gain_max_ << std::endl;
    return;
}

Bool_t ImplantTSScannor::IsInGate()
{
    auto pspmt_low = tree_data_->Get()->low_gain_;
    if(!pspmt_low.valid_)
        return false;
    //if(pspmt_low.energy_ < 2000 || pspmt_low.energy_ > 8000 )
    //    return false;

    // Anti-gating on veto
    {
        const Double_t tdiff_first = tree_data_->Get()->veto_first_.time_ - pspmt_low.time_ + 100.;
        const Double_t tdiff_second = tree_data_->Get()->veto_second_.time_ - pspmt_low.time_ + 100.;
        if(tdiff_first<10.&&tdiff_first>-10.&&tdiff_second<10.&&tdiff_second>-10.)
            return false;
    }

    // Gating on dE Si
    {
        const Double_t tdiff_top = tree_data_->Get()->desi_top_.time_ - pspmt_low.time_ + 95.;
        const Double_t de_top = tree_data_->Get()->desi_top_.energy_;
        const Double_t tdiff_bottom = tree_data_->Get()->desi_bottom_.time_ - pspmt_low.time_ + 95.;
        const Double_t de_bottom = tree_data_->Get()->desi_bottom_.energy_;

        if( tdiff_top<10. && tdiff_top>-10. && de_top>5200. && de_top<5600. ) //83Ga
            return true;
        else if ( tdiff_bottom<10. && tdiff_bottom>-10. && de_bottom>5600. && de_bottom<6400. ) //83Ga
            return true;
        else
            return false;
    }
}

const std::string MergedImplantTSScannor::kMsgPrefix("[MergedImplantTSScannor]:");

void MergedImplantTSScannor::SetReader()
{
    TSScannorBase<OutputTreeData<PspmtData, TreeData>>::SetReader();
    std::string br_name = yaml_reader_->GetString("PixieBranchName");
    tree_data_ = new TTreeReaderValue<OutputTreeData<PspmtData, TreeData>>(*tree_reader_,br_name.c_str());
    std::cout << kMsgPrefix << "TTreeReaderValue: " << br_name << " created." << std::endl;

    return;
}

Bool_t MergedImplantTSScannor::IsInGate()
{
    if(tree_data_->Get()->output_vec_.size()==0)
        return false;
    else
        return true;
}